<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/418_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:

import numpy as np
import tensorflow as tf

np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}".format(x)})

I = np.array([[.05,.10]])
T = np.array([[0,1]])

WH = np.array([[.15,.25],
              [.20,.30]])
BH = np.array([.35,.35])
WO = np.array([[.40,.50],
               [.45,.55]])
BO = np.array([.60,.60])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, input_shape=(2,), activation= 'relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

model.layers[0].set_weights([WH, BH])
model.layers[1].set_weights([WO, BO])


optimizer=tf.keras.optimizers.SGD(learning_rate=0.01)
loss=tf.keras.losses.CategoricalCrossentropy()

for epoch in range(200):
  print('epoch = %d' %epoch)

  with tf.GradientTape() as tape:

    O = model(I)
    print('O=', O.numpy())
    E = loss(T,O)

  gradients = tape.gradient(E, model.trainable_variables)

  optimizer.apply_gradients(zip(gradients, model.trainable_variables))
  print('WH=\n', model.layers[0].get_weights()[0])
  print('BH=\n', model.layers[0].get_weights()[1])
  print('WO=\n', model.layers[1].get_weights()[0])
  print('BO=\n', model.layers[1].get_weights()[1])

epoch = 0
O= [[ 0.481  0.519]]
WH=
 [[ 0.150  0.250]
 [ 0.200  0.300]]
BH=
 [ 0.350  0.350]
WO=
 [[ 0.398  0.502]
 [ 0.448  0.552]]
BO=
 [ 0.595  0.605]
epoch = 1
O= [[ 0.478  0.522]]
WH=
 [[ 0.150  0.250]
 [ 0.200  0.300]]
BH=
 [ 0.351  0.351]
WO=
 [[ 0.396  0.504]
 [ 0.446  0.554]]
BO=
 [ 0.590  0.610]
epoch = 2
O= [[ 0.475  0.525]]
WH=
 [[ 0.150  0.250]
 [ 0.200  0.300]]
BH=
 [ 0.351  0.351]
WO=
 [[ 0.395  0.505]
 [ 0.444  0.556]]
BO=
 [ 0.586  0.614]
epoch = 3
O= [[ 0.471  0.529]]
WH=
 [[ 0.150  0.250]
 [ 0.200  0.300]]
BH=
 [ 0.352  0.352]
WO=
 [[ 0.393  0.507]
 [ 0.443  0.557]]
BO=
 [ 0.581  0.619]
epoch = 4
O= [[ 0.468  0.532]]
WH=
 [[ 0.150  0.250]
 [ 0.200  0.300]]
BH=
 [ 0.353  0.353]
WO=
 [[ 0.391  0.509]
 [ 0.441  0.559]]
BO=
 [ 0.576  0.624]
epoch = 5
O= [[ 0.465  0.535]]
WH=
 [[ 0.150  0.250]
 [ 0.200  0.300]]
BH=
 [ 0.353  0.353]
WO=
 [[ 0.389  0.511]
 [ 0.439  0.561]]
BO=
 [ 0.572  0.628]
epoch = 6
O= [[ 0.462  0.538]]
WH=
 [[ 0.150  0.250]
 [ 0.200  0.300]]
BH=
 [ 0.35