<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/5110_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(4,4,3))
print('image_0=\n', image[:,:,0])
print('image_1=\n', image[:,:,1])
print('image_2=\n', image[:,:,2])

filter = np.random.randint(5, size=(3,3,3,2))
print('filter_00=\n', filter[:,:,0,0])
print('filter_01=\n', filter[:,:,1,0])
print('filter_02=\n', filter[:,:,2,0])
print('filter_10=\n', filter[:,:,0,1])
print('filter_11=\n', filter[:,:,1,1])
print('filter_12=\n', filter[:,:,2,1])

image_pad = np.pad(image, ((1,1),(1,1),(0,0)))
print('image_pad_0=\n', image_pad[:,:,0])
print('image_pad_1=\n', image_pad[:,:,1])
print('image_pad_2=\n', image_pad[:,:,2])

convolution = np.zeros((4,4,2))

for fn in range(2):
  for row in range(4):
    for col in range(4):
      window = image_pad[row:row+3, col:col+3]
      convolution[row, col, fn] = np.sum(window*filter[:, :, :, fn])


print('convolution_0=\n', convolution[:,:,0])
print('convolution_1=\n', convolution[:,:,1])

image_0=
 [[3 1 0 4]
 [4 3 4 1]
 [1 1 1 3]
 [0 1 0 4]]
image_1=
 [[4 3 1 1]
 [2 4 2 1]
 [1 0 0 2]
 [3 3 1 2]]
image_2=
 [[0 0 4 2]
 [4 2 4 0]
 [1 4 0 1]
 [1 4 3 4]]
filter_00=
 [[0 1 3]
 [0 2 0]
 [3 4 0]]
filter_01=
 [[1 2 3]
 [2 0 4]
 [3 1 4]]
filter_02=
 [[0 0 3]
 [3 1 4]
 [3 4 1]]
filter_10=
 [[3 2 4]
 [2 0 0]
 [0 4 2]]
filter_11=
 [[2 1 1]
 [1 1 2]
 [4 0 1]]
filter_12=
 [[4 1 0]
 [4 3 3]
 [4 2 0]]
image_pad_0=
 [[0 0 0 0 0 0]
 [0 3 1 0 4 0]
 [0 4 3 4 1 0]
 [0 1 1 1 3 0]
 [0 0 1 0 4 0]
 [0 0 0 0 0 0]]
image_pad_1=
 [[0 0 0 0 0 0]
 [0 4 3 1 1 0]
 [0 2 4 2 1 0]
 [0 1 0 0 2 0]
 [0 3 3 1 2 0]
 [0 0 0 0 0 0]]
image_pad_2=
 [[0 0 0 0 0 0]
 [0 0 0 4 2 0]
 [0 4 2 4 0 0]
 [0 1 4 0 1 0]
 [0 1 4 3 4 0]
 [0 0 0 0 0 0]]
convolution_0=
 [[ 70.  96.  87.  59.]
 [ 72. 103.  84.  46.]
 [ 77.  96.  93.  58.]
 [ 47.  36.  64.  30.]]
convolution_1=
 [[ 44.  77.  77.  52.]
 [ 53.  97.  93.  70.]
 [ 53. 110. 113.  82.]
 [ 32.  52.  82.  39.]]
