<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/512_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(3,3))
print('image=\n', image)

filter = np.random.randint(5, size=(3,3))
print('filter=\n', filter)

image_x_filter = image * filter
print('image_x_filter=\n', image_x_filter)

convolution = np.sum(image_x_filter)
print('convolution=\n', convolution)

image=
 [[3 4 0]
 [1 3 0]
 [0 1 4]]
filter=
 [[4 1 2]
 [4 2 4]
 [3 4 2]]
image_x_filter=
 [[12  4  0]
 [ 4  6  0]
 [ 0  4  8]]
convolution=
 38
