<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/513_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(4,4))
print('image=\n, image')

filter = np.random.randint(5, size=(3,3))
print('filter=\n', filter)

convolution = np.zeros((2,2))

for row in range(2):
  for col in range(2):
    window = image[row:row+3, col:col+3]
    print('window(%d, %d) =\n' %(row, col), window)
    print('window(%d, %d)*filter =\n' %(row,col), window*filter)
    convolution[row, col] = np.sum(window*filter)

print('convolution =\n', convolution)



image=
, image
filter=
 [[4 2 4]
 [2 4 1]
 [1 0 1]]
window(0, 0) =
 [[3 4 0]
 [3 0 0]
 [4 4 1]]
window(0, 0)*filter =
 [[12  8  0]
 [ 6  0  0]
 [ 4  0  1]]
window(0, 1) =
 [[4 0 1]
 [0 0 1]
 [4 1 2]]
window(0, 1)*filter =
 [[16  0  4]
 [ 0  0  1]
 [ 4  0  2]]
window(1, 0) =
 [[3 0 0]
 [4 4 1]
 [4 2 4]]
window(1, 0)*filter =
 [[12  0  0]
 [ 8 16  1]
 [ 4  0  4]]
window(1, 1) =
 [[0 0 1]
 [4 1 2]
 [2 4 3]]
window(1, 1)*filter =
 [[0 0 4]
 [8 4 2]
 [2 0 3]]
convolution =
 [[31. 27.]
 [45. 23.]]
