<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/514_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(4,4))
print('image=\n', image)

filter = np.random.randint(5, size=(3,3))
print('filter=\n', filter)

image_pad = np.pad(image,((1,1),(1,1)))
print('image_pad=\n', image_pad)

convolution = np.zeros((4,4))

for row in range(4):
  for col in range(4):
    windows = image_pad[row:row+3, col:col+3]
    convolution[row, col] = np.sum(windows*filter)


print('convolution=\n', convolution)

image=
 [[3 4 0 1]
 [3 0 0 1]
 [4 4 1 2]
 [4 2 4 3]]
filter=
 [[4 2 4]
 [2 4 1]
 [1 0 1]]
image_pad=
 [[0 0 0 0 0 0]
 [0 3 4 0 1 0]
 [0 3 0 0 1 0]
 [0 4 4 1 2 0]
 [0 4 2 4 3 0]
 [0 0 0 0 0 0]]
convolution=
 [[16. 25. 10.  4.]
 [38. 31. 27.  7.]
 [28. 45. 23. 16.]
 [42. 48. 49. 28.]]
