<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/516_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(4,4))
print('image=\n', image)

filter = np.random.randint(5, size=(3,3,2))
print('filter_0=\n', filter[:,:,0])
print('filter_1=\n', filter[:,:,1])

image_pad = np.pad(image,((1,1),(1,1)))
print('image_pad=\n', image_pad)

convolution = np.zeros((4,4,2))

for fn in range(2):
  for row in range(4):
    for col in range(4):
       windows = image_pad[row:row+3, col:col+3]
       convolution[row, col, fn] = np.sum(windows*filter[:,:,fn])

print('convolution_0=\n', convolution[:,:,0])
print('convolution_1=\n', convolution[:,:,1])

max_pooled = np.zeros((2,2,2))

for fn in range(2):
  for row in range(0,2):
    for col in range(0,2):
       window = convolution[2*row:2*row+2, 2*col:2*col+2, fn]
       max_pooled[row, col, fn] = np.max(window)

print('max_pooled_0=\n', max_pooled[:,:,0])
print('max_pooled_1=\n', max_pooled[:,:,1])

image=
 [[3 4 0 1]
 [3 0 0 1]
 [4 4 1 2]
 [4 2 4 3]]
filter_0=
 [[4 4 4]
 [1 1 1]
 [0 1 0]]
filter_1=
 [[2 2 1]
 [0 1 1]
 [4 0 3]]
image_pad=
 [[0 0 0 0 0 0]
 [0 3 4 0 1 0]
 [0 3 0 0 1 0]
 [0 4 4 1 2 0]
 [0 4 2 4 3 0]
 [0 0 0 0 0 0]]
convolution_0=
 [[10.  7.  5.  2.]
 [35. 35. 22.  7.]
 [24. 23. 15. 10.]
 [38. 46. 37. 19.]]
convolution_1=
 [[ 7. 16.  4.  1.]
 [25. 33. 32.  7.]
 [20. 39. 21. 20.]
 [18. 23. 19.  9.]]
max_pooled_0=
 [[35. 22.]
 [46. 37.]]
max_pooled_1=
 [[33. 32.]
 [39. 21.]]
