<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/518_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np

np.random.seed(1)

image = np.random.randint(5, size=(3,3,2))
print('image_0=\n', image[:,:,0])
print('image_1=\n', image[:,:,1])

filter = np.random.randint(5, size=(3,3,2))
print('filter_0=\n', filter[:,:,0])
print('filter_1=\n', filter[:,:,1])

image_x_filter = image*filter
print('image_x_filter_0=\n', image_x_filter[:,:,0])
print('image_x_filter_1=\n', image_x_filter[:,:,1])

convolution = np.sum(image_x_filter)
print('convolution=\n', convolution)


image_0=
 [[3 0 3]
 [0 4 1]
 [4 4 4]]
image_1=
 [[4 1 0]
 [1 4 2]
 [2 3 2]]
filter_0=
 [[4 4 1]
 [1 1 0]
 [1 0 2]]
filter_1=
 [[2 1 0]
 [1 1 4]
 [0 3 1]]
image_x_filter_0=
 [[12  0  3]
 [ 0  4  0]
 [ 4  0  8]]
image_x_filter_1=
 [[8 1 0]
 [1 4 8]
 [0 9 2]]
convolution=
 64
