<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/534_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

np.random.seed(1)

X = np.random.randint(5, size=(3,3))
print('X=\n', X)

W = np.random.randint(5, size=(3,3))
print('W=\n', W)

b = 0
print('b=', b)

y = np.sum(X*W)+b
print('y=', y)

yb = np.random.randint(-5,5)
print('yb=', yb)

Wb = yb*X
print('Wb =\n',Wb)

bb = yb
print('bb=',bb)

Xb = yb*W
print('Xb=\n', Xb)



X=
 [[3 4 0]
 [1 3 0]
 [0 1 4]]
W=
 [[4 1 2]
 [4 2 4]
 [3 4 2]]
b= 0
y= 38
yb= -3
Wb =
 [[ -9 -12   0]
 [ -3  -9   0]
 [  0  -3 -12]]
bb= -3
Xb=
 [[-12  -3  -6]
 [-12  -6 -12]
 [ -9 -12  -6]]
