<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/536_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

np.random.seed(1)

X = np.random.randint(5, size=(4,4))
print('X=\n', X)

W = np.random.randint(5, size=(3,3))
print('W=\n', W)

b = 0
print('b=', b)
XP = np.pad(X,((1,1),(1,1)))
print('XP=\n', XP)

Y = np.zeros((4,4))

for row in range(4):
  for col in range(4):
    winXP = XP[row:row+3, col:col+3]
    Y[row, col] = np.sum(winXP*W)+b

print('Y=\n', Y)

Yb = np.random.randint(-8,5,size=Y.shape)
print('Yb=\n', Y)
Wb = np.zeros_like(W)

for row in range(4):
  for col in range(4):
    winXP = XP[row:row+3, col:col+3]
    Wb+=winXP*Yb[row, col]

print('Wb=\n', Wb)

bb = np.sum(Yb)
print('bb=', bb)

XPb = np.zeros_like(XP)

for row in range(4):
  for col in range(4):
    winXPb= XPb[row:row+3, col:col+3]
    winXPb+=Yb[row, col]*W

print('XPb=\n', XPb)

Xb = XPb[1:-1,1:-1]
print('Xb=\n', Xb)




X=
 [[3 4 0 1]
 [3 0 0 1]
 [4 4 1 2]
 [4 2 4 3]]
W=
 [[4 2 4]
 [2 4 1]
 [1 0 1]]
b= 0
XP=
 [[0 0 0 0 0 0]
 [0 3 4 0 1 0]
 [0 3 0 0 1 0]
 [0 4 4 1 2 0]
 [0 4 2 4 3 0]
 [0 0 0 0 0 0]]
Y=
 [[16. 25. 10.  4.]
 [38. 31. 27.  7.]
 [28. 45. 23. 16.]
 [42. 48. 49. 28.]]
Yb=
 [[16. 25. 10.  4.]
 [38. 31. 27.  7.]
 [28. 45. 23. 16.]
 [42. 48. 49. 28.]]
Wb=
 [[-17 -65 -27]
 [-75 -44  -5]
 [-28 -80 -45]]
bb= -27
XPb=
 [[  4  -2  -6  -4  -6   4]
 [-26 -44 -35 -59   4 -27]
 [-13 -45 -52  -8 -42   2]
 [ -3  -6 -13 -53  -7 -25]
 [  2   4  -6 -12 -26  -3]
 [  1   0   0  -5  -1  -5]]
Xb=
 [[-44 -35 -59   4]
 [-45 -52  -8 -42]
 [ -6 -13 -53  -7]
 [  4  -6 -12 -26]]
