<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/537_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

np.random.seed(1)

X = np.random.randint(5, size=(4,4))
print('X=\n', X)

W = np.random.randint(5, size=(3,3))
print('W=\n', W)

b = 0
print('b=', b)
XP = np.pad(X,((1,1),(1,1)))
print('XP=\n', XP)

Y = np.zeros((4,4))

for row in range(4):
  for col in range(4):
    winXP = XP[row:row+3, col:col+3]
    Y[row, col] = np.sum(winXP*W)+b

print('Y=\n', Y)
MP = np.zeros((2,2))

for row in range(0,2):
  for col in range(0,2):
    winY = Y[2*row:2*row+2, 2*col:2*col+2]
    MP[row, col]=np.max(winY)


print('MP=\n', MP)

MPb = np.random.randint(-8,5, size=MP.shape)
print('MPb=\n', MPb)
Yb = np.zeros_like(Y)

for row in range(0,2):
  for col in range(0,2):
    winY = Y[2*row:2*row+2, 2*col:2*col+2]
    winYb = Yb[2*row:2*row+2, 2*col:2*col+2]
    winYb[winY==np.max(winY)]=MPb[row,col]
print('Yb=\n',Yb)
Wb = np.zeros_like(W)/1

for row in range(4):
  for col in range(4):
    winXP= XP[row:row+3, col:col+3]
    Wb+=winXP*Yb[row, col]

print('Wb=\n', Wb)

bb = np.sum(Yb)
print('bb=', bb)

XPb = np.zeros_like(XP)/1

for row in range(4):
  for col in range(4):
    winXPb= XPb[row:row+3, col:col+3]
    winXPb+=Yb[row, col]*W

print('XPb=\n', XPb)
Xb = XPb[1:-1,1:-1]
print('Xb=\n', Xb)


X=
 [[3 4 0 1]
 [3 0 0 1]
 [4 4 1 2]
 [4 2 4 3]]
W=
 [[4 2 4]
 [2 4 1]
 [1 0 1]]
b= 0
XP=
 [[0 0 0 0 0 0]
 [0 3 4 0 1 0]
 [0 3 0 0 1 0]
 [0 4 4 1 2 0]
 [0 4 2 4 3 0]
 [0 0 0 0 0 0]]
Y=
 [[16. 25. 10.  4.]
 [38. 31. 27.  7.]
 [28. 45. 23. 16.]
 [42. 48. 49. 28.]]
MP=
 [[38. 27.]
 [48. 49.]]
MPb=
 [[ 1 -1]
 [-2  1]]
Yb=
 [[ 0.  0.  0.  0.]
 [ 1.  0. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0. -2.  1.  0.]]
Wb=
 [[-8. -4.  3.]
 [-6.  3. -6.]
 [-4.  3.  2.]]
bb= -1.0
XPb=
 [[ 0.  0.  0.  0.  0.  0.]
 [ 4.  2.  0. -2. -4.  0.]
 [ 2.  4. -1. -4. -1.  0.]
 [ 1. -8.  0. -6.  3.  0.]
 [ 0. -4. -6.  2.  1.  0.]
 [ 0. -2.  1. -2.  1.  0.]]
Xb=
 [[ 2.  0. -2. -4.]
 [ 4. -1. -4. -1.]
 [-8.  0. -6.  3.]
 [-4. -6.  2.  1.]]
