<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/621_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}".format(x)})

IMG_SIZE = 4
HALF_SIZE = int(IMG_SIZE/2)

I_DEPTH = 1
C_DEPTH = 2
K_SIZE = 3
P_SIZE = 2
NUM_OUT = 3

np.random.seed(1)

I = np.random.rand(1,IMG_SIZE, IMG_SIZE, I_DEPTH)
WC = np.random.rand(K_SIZE, K_SIZE, I_DEPTH, C_DEPTH)
"""합성곱에서 사용할 필터를 가르키는 변수.
   CNN에서 필터는 학습의 대상이 되는 가중치"""
BC = np.random.rand(C_DEPTH,)
"""편향을 가리키는 변수. 출력층의 깊이와 같음."""
WO = np.random.rand(HALF_SIZE*HALF_SIZE*C_DEPTH, NUM_OUT)
"""완전 연결층에서 입력 층과 출력 층 사이에 사용할 가중치"""
BO = np.random.rand(1, NUM_OUT)
"""완전 연결층에서 입력 층과 출력 층 사이에 사용할 편향"""
T = np.zeros((1,NUM_OUT))
"""목표값"""
C = np.zeros((IMG_SIZE, IMG_SIZE, C_DEPTH))
P = np.zeros((HALF_SIZE, HALF_SIZE, C_DEPTH))

IP = np.pad(I, ((0,0),(1,1),(1,1),(0,0)))

print('IP=\n', IP[0,:,:,0])



IP=
 [[ 0.000  0.000  0.000  0.000  0.000  0.000]
 [ 0.000  0.417  0.720  0.000  0.302  0.000]
 [ 0.000  0.147  0.092  0.186  0.346  0.000]
 [ 0.000  0.397  0.539  0.419  0.685  0.000]
 [ 0.000  0.204  0.878  0.027  0.670  0.000]
 [ 0.000  0.000  0.000  0.000  0.000  0.000]]
