<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/613_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import tensorflow as tf
import numpy as np

np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}".format(x)})

IMG_SIZE = 4
HALF_SIZE = int(IMG_SIZE/2)

I_DEPTH = 1
C_DEPTH = 2
K_SIZE = 3
NUM_OUT = 3

np.random.seed(1)

I = np.random.rand(1,IMG_SIZE, IMG_SIZE, I_DEPTH)
WC = np.random.rand(K_SIZE, K_SIZE, I_DEPTH, C_DEPTH)
"""합성곱에서 사용할 필터를 가르키는 변수.
   CNN에서 필터는 학습의 대상이 되는 가중치"""
BC = np.random.rand(C_DEPTH,)
"""편향을 가리키는 변수. 출력층의 깊이와 같음."""
WO = np.random.rand(HALF_SIZE*HALF_SIZE*C_DEPTH, NUM_OUT)
"""완전 연결층에서 입력 층과 출력 층 사이에 사용할 가중치"""
BO = np.random.rand(NUM_OUT,)
"""완전 연결층에서 입력 층과 출력 층 사이에 사용할 편향"""
T = np.zeros((1,NUM_OUT))
"""목표값"""

model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(IMG_SIZE, IMG_SIZE, I_DEPTH)),
    tf.keras.layers.Conv2D(C_DEPTH, (K_SIZE, K_SIZE), padding='same'),
])

model.layers[0].set_weights([WC, BC])

optimizer=tf.keras.optimizers.SGD(learning_rate=0.01)
loss=tf.keras.losses.MeanSquaredError()

for epoch in range(1):
  with tf.GradientTape() as tape:
    O = model(I)
    print('O_0=\n', O.numpy()[0,:,:,0])
    print('O_1=\n', O.numpy()[0,:,:,1])
    print('O.shape=',O.shape)





O_0=
 [[ 1.221  1.666  1.308  1.022]
 [ 2.019  1.632  2.245  1.234]
 [ 2.041  1.695  2.422  1.621]
 [ 1.433  2.105  1.881  1.559]]
O_1=
 [[ 0.828  1.516  1.170  0.895]
 [ 1.685  1.682  2.270  1.470]
 [ 1.364  1.933  2.654  1.698]
 [ 1.133  1.978  2.022  1.304]]
O.shape= (1, 4, 4, 2)
