<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/618_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import tensorflow as tf
import numpy as np

np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}".format(x)})

IMG_SIZE = 4
HALF_SIZE = int(IMG_SIZE/2)

I_DEPTH = 1
C_DEPTH = 2
K_SIZE = 3
NUM_OUT = 3

np.random.seed(1)

I = np.random.rand(1,IMG_SIZE,IMG_SIZE,I_DEPTH)
WC = np.random.rand(K_SIZE,K_SIZE,I_DEPTH,C_DEPTH)
"""합성곱에서 사용할 필터를 가르키는 변수.
   CNN에서 필터는 학습의 대상이 되는 가중치"""
BC = np.random.rand(C_DEPTH,)
"""편향을 가리키는 변수. 출력층의 깊이와 같음."""
WO = np.random.rand(HALF_SIZE*HALF_SIZE*C_DEPTH,NUM_OUT)
"""완전 연결층에서 입력 층과 출력 층 사이에 사용할 가중치"""
BO = np.random.rand(NUM_OUT,)
"""완전 연결층에서 입력 층과 출력 층 사이에 사용할 편향"""
T = np.zeros((1,NUM_OUT))
"""목표값"""


model = tf.keras.Sequential([
	  tf.keras.layers.InputLayer(input_shape=(IMG_SIZE, IMG_SIZE, I_DEPTH)),
    tf.keras.layers.Conv2D(C_DEPTH, (K_SIZE, K_SIZE), padding='same'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(NUM_OUT),
])
model.layers[0].set_weights([WC, BC])
model.layers[3].set_weights([WO, BO])
optimizer=tf.keras.optimizers.SGD(learning_rate=0.01)
loss=tf.keras.losses.MeanSquaredError()

for epoch in range(1):

  with tf.GradientTape() as tape:

    O = model(I)

    E = loss(T, O)

  gradients = tape.gradient(E, model.trainable_variables)
  print('len(gradients)=',len(gradients))
  print('WOb =\n', gradients[2].numpy()[:,0])
  print('BOb =\n', gradients[3].numpy())
  print('WCb_0 =\n', gradients[0].numpy()[:,:,0,0])
  print('WCb_1 =\n', gradients[0].numpy()[:,:,0,1])
  print('BCb=\n', gradients[1].numpy())






len(gradients)= 4
WOb =
 [10.668  8.904 11.865 11.995 11.122 10.453 12.798 14.022]
BOb =
 [ 5.284  6.657  4.469]
WCb_0 =
 [[ 6.675  6.225 11.794]
 [ 4.144  7.185  7.192]
 [ 8.724  6.844 13.624]]
WCb_1 =
 [[10.182 10.582 18.242]
 [ 6.379 12.560 10.175]
 [12.113  9.803 19.396]]
BCb=
 [24.454 37.625]
