<a href="https://colab.research.google.com/github/Flowergift/Python_AI_Sample/blob/main/625_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import numpy as np
import sys
sys.path.append('/content/sample_data/my_cnn2D.py')
sys.path.append('/content/sample_data/my_cnn3D.py')

from my_cnn3D import*
from my_cnn2D import*


np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}".format(x)})

IMG_SIZE = 28 #
HALF_SIZE = int(IMG_SIZE/2)

I_DEPTH = 1
C_DEPTH = 32 #
K_SIZE = 3
P_SIZE = 2
NUM_OUT = 10 #

np.random.seed(1)

I = np.random.rand(1,IMG_SIZE,IMG_SIZE,I_DEPTH)
WC = np.random.rand(K_SIZE,K_SIZE,I_DEPTH,C_DEPTH)
BC = np.random.rand(C_DEPTH,)

WO = np.random.rand(HALF_SIZE*HALF_SIZE*C_DEPTH,NUM_OUT)
BO = np.random.rand(1, NUM_OUT)

T = np.zeros((1, NUM_OUT))

for epoch in range(1): #

	C, cache = conv_2D_f(I[0], WC, BC)
	C = (C>0)*C # relu

	P = max_pool_3D_f(C)

	(p_size, _, p_depth) = P.shape
	F = P.reshape((1,p_size*p_size*p_depth))

	O = F@WO + BO
	OM = O - np.max(O) #
	O = np.exp(OM)/np.sum(np.exp(OM)) # softmax
	print('O =\n', O) #

	E = np.sum(-T*np.log(O)) #
	print('E =\n', E) #

	Ob = (O-T) #
	# nothing for softmax

	WOb = F.T@Ob
	BOb = Ob

	Fb = Ob@WO.T

	Pb = Fb.reshape(P.shape)

	Cb = max_pool_3D_b(Pb, C)
	Cb = Cb*(C>0)*1 # relu

	WCb, BCb, Ib = conv_2D_b(Cb, I[0], WC, BC, cache, input_back=False)

	lr = 0.01
	WO -= lr*WOb
	BO -= lr*BOb
	WC -= lr*WCb
	BC -= lr*BCb

print('WO =\n', WO[:,0])
print('BO =\n', BO)
print('WC_0 =\n', WC[:,:,0,0])
print('WC_1 =\n', WC[:,:,0,1])
print('BC =\n', BC)

O =
 [[ 0.000  0.000  0.000  0.000  0.000  1.000  0.000  0.000  0.000  0.000]]
E =
 0.0
WO =
 [ 0.918  0.127  0.293 ...  0.965  0.344  0.300]
BO =
 [[ 0.300  0.915  0.872  0.209  0.599  0.671  0.475  0.619  0.909  0.459]]
WC_0 =
 [[ 0.014 -0.159 -0.134]
 [-0.119  0.012 -0.249]
 [-0.257 -0.400 -0.419]]
WC_1 =
 [[-0.141 -0.333 -0.259]
 [-0.220  0.370  0.200]
 [-0.061  0.156 -0.054]]
BC =
 [-0.774 -0.156 -0.066 -0.509 -0.353 -0.376 -0.388 -0.146 -0.778 -0.112
 -0.423 -0.834 -0.741 -0.424 -0.789 -0.859 -0.859 -0.115 -0.395 -0.076
 -0.645 -0.468 -0.358 -0.402 -0.922 -0.218 -0.078 -0.465 -0.838 -0.225
 -0.942 -0.612]
